import type { HttpTransport } from '../../../shared/api/http'
import {
  fromAddressDto, fromAmendmentDto, fromClinicalItemDto, fromDiagnosisDto, fromEmergencyContactDto, fromEncounterDto, fromMedicalHistoryDto, fromNoteDto, fromOdontogramDto, fromOdontogramEntryDto,
  type Address, type AddressDraft, type ClinicalEncounter, type ClinicalItem, type ClinicalItemDraft, type ClinicalItemKind, type ClinicalNote, type ClinicalNoteAmendment, type ClinicalNoteDraft, type EmergencyContact, type EmergencyContactDraft, type EncounterDiagnosis, type MedicalHistory, type MedicalHistoryDraft, type Odontogram, type OdontogramEntry, type ToothSurface,
} from '../domain/clinical'

const nullable = (value: string | undefined) => value?.trim() || null
const patientPath = (patientId: string, resource: string) => `/api/v1/patients/${encodeURIComponent(patientId)}/${resource}`
const id = (value: string) => encodeURIComponent(value)

export interface ClinicalApi {
  listAddresses: (patientId: string, signal?: AbortSignal) => Promise<Address[]>; createAddress: (patientId: string, draft: AddressDraft) => Promise<Address>; updateAddress: (patientId: string, resourceId: string, patch: Partial<AddressDraft>) => Promise<Address>
  listEmergencyContacts: (patientId: string, signal?: AbortSignal) => Promise<EmergencyContact[]>; createEmergencyContact: (patientId: string, draft: EmergencyContactDraft) => Promise<EmergencyContact>; updateEmergencyContact: (patientId: string, resourceId: string, patch: Partial<EmergencyContactDraft>) => Promise<EmergencyContact>
  listMedicalHistory: (patientId: string, signal?: AbortSignal) => Promise<MedicalHistory[]>; createMedicalHistory: (patientId: string, draft: MedicalHistoryDraft) => Promise<MedicalHistory>
  listItems: (patientId: string, kind: ClinicalItemKind, signal?: AbortSignal) => Promise<ClinicalItem[]>; createItem: (patientId: string, kind: ClinicalItemKind, draft: Partial<ClinicalItemDraft> & Pick<ClinicalItemDraft, 'name'>) => Promise<ClinicalItem>; updateItem: (patientId: string, kind: ClinicalItemKind, resourceId: string, patch: Partial<ClinicalItemDraft>) => Promise<ClinicalItem>
  listEncounters: (patientId: string, signal?: AbortSignal) => Promise<ClinicalEncounter[]>; createEncounter: (input: { patientId: string; providerUserId: string; startedAt: string; appointmentId?: string }) => Promise<ClinicalEncounter>; getEncounter: (encounterId: string, signal?: AbortSignal) => Promise<ClinicalEncounter>; completeEncounter: (encounterId: string, version: number) => Promise<ClinicalEncounter>; voidEncounter: (encounterId: string, version: number, reason: string) => Promise<ClinicalEncounter>
  listDiagnoses: (encounterId: string, signal?: AbortSignal) => Promise<EncounterDiagnosis[]>; createDiagnosis: (encounterId: string, input: { description: string; codeSystem?: string; code?: string; toothNumber?: number; diagnosisType?: string }) => Promise<EncounterDiagnosis>
  listNotes: (encounterId: string, signal?: AbortSignal) => Promise<ClinicalNote[]>; createNote: (draft: ClinicalNoteDraft & { encounterId: string }) => Promise<ClinicalNote>; getNote: (noteId: string, signal?: AbortSignal) => Promise<ClinicalNote>; updateNote: (noteId: string, version: number, draft: ClinicalNoteDraft) => Promise<ClinicalNote>; signNote: (noteId: string, version: number) => Promise<ClinicalNote>; listAmendments: (noteId: string, signal?: AbortSignal) => Promise<ClinicalNoteAmendment[]>; addAmendment: (noteId: string, version: number, input: { reason: string; amendmentText: string }) => Promise<{ amendment: ClinicalNoteAmendment; note: ClinicalNote }>
  listOdontograms: (patientId: string, signal?: AbortSignal) => Promise<Odontogram[]>; createOdontogram: (input: { patientId: string; encounterId?: string }) => Promise<Odontogram>; getOdontogram: (odontogramId: string, signal?: AbortSignal) => Promise<Odontogram>; listOdontogramEntries: (odontogramId: string, signal?: AbortSignal) => Promise<OdontogramEntry[]>; createOdontogramEntry: (odontogramId: string, version: number, input: { toothNumber: number; surface: ToothSurface; conditionCode?: string; status?: string; notes?: string }) => Promise<OdontogramEntry>; signOdontogram: (odontogramId: string, version: number) => Promise<Odontogram>
}

function list<T>(http: HttpTransport, path: string, map: (dto: any) => T, signal?: AbortSignal): Promise<T[]> { return http.get<{ items?: any[] }>(path, signal ? { signal } : undefined).then((payload) => Array.isArray(payload.items) ? payload.items.map(map) : []) }
function addressWrite(draft: Partial<AddressDraft>) { return { ...(draft.addressType !== undefined ? { address_type: draft.addressType } : {}), ...(draft.street !== undefined ? { street: nullable(draft.street) } : {}), ...(draft.exteriorNumber !== undefined ? { exterior_number: nullable(draft.exteriorNumber) } : {}), ...(draft.interiorNumber !== undefined ? { interior_number: nullable(draft.interiorNumber) } : {}), ...(draft.neighborhood !== undefined ? { neighborhood: nullable(draft.neighborhood) } : {}), ...(draft.municipality !== undefined ? { municipality: nullable(draft.municipality) } : {}), ...(draft.state !== undefined ? { state: nullable(draft.state) } : {}), ...(draft.postalCode !== undefined ? { postal_code: nullable(draft.postalCode) } : {}), ...(draft.countryCode !== undefined ? { country_code: draft.countryCode.trim().toUpperCase() } : {}), ...(draft.isPrimary !== undefined ? { is_primary: draft.isPrimary } : {}) } }
function contactWrite(draft: Partial<EmergencyContactDraft>) { return { ...(draft.name !== undefined ? { name: draft.name.trim() } : {}), ...(draft.relationship !== undefined ? { relationship: nullable(draft.relationship) } : {}), ...(draft.phoneE164 !== undefined ? { phone_e164: draft.phoneE164.trim() } : {}), ...(draft.isPrimary !== undefined ? { is_primary: draft.isPrimary } : {}) } }
function itemWrite(draft: Partial<ClinicalItemDraft>) { return { ...(draft.name !== undefined ? { name: draft.name.trim() } : {}), ...(draft.codeSystem !== undefined ? { code_system: nullable(draft.codeSystem) } : {}), ...(draft.code !== undefined ? { code: nullable(draft.code) } : {}), ...(draft.reaction !== undefined ? { reaction: nullable(draft.reaction) } : {}), ...(draft.severity !== undefined ? { severity: nullable(draft.severity) } : {}), ...(draft.dose !== undefined ? { dose: nullable(draft.dose) } : {}), ...(draft.frequency !== undefined ? { frequency: nullable(draft.frequency) } : {}), ...(draft.diagnosedOn !== undefined ? { diagnosed_on: nullable(draft.diagnosedOn) } : {}), ...(draft.startedOn !== undefined ? { started_on: nullable(draft.startedOn) } : {}), ...(draft.endedOn !== undefined ? { ended_on: nullable(draft.endedOn) } : {}), ...(draft.isActive !== undefined ? { is_active: draft.isActive } : {}), ...(draft.notes !== undefined ? { notes: nullable(draft.notes) } : {}) } }
function noteWrite(draft: ClinicalNoteDraft) { return { ...(draft.encounterId ? { encounter_id: draft.encounterId } : {}), note_type: draft.noteType.trim(), ...(draft.subjective !== undefined ? { subjective: nullable(draft.subjective) } : {}), ...(draft.objective !== undefined ? { objective: nullable(draft.objective) } : {}), ...(draft.assessment !== undefined ? { assessment: nullable(draft.assessment) } : {}), ...(draft.plan !== undefined ? { plan: nullable(draft.plan) } : {}), ...(draft.additionalNotes !== undefined ? { additional_notes: nullable(draft.additionalNotes) } : {}) } }

export function createClinicalApi(http: HttpTransport): ClinicalApi { return {
  listAddresses: (patientId, signal) => list(http, patientPath(patientId, 'addresses'), fromAddressDto, signal), createAddress: async (patientId, draft) => fromAddressDto(await http.post(patientPath(patientId, 'addresses'), addressWrite(draft))), updateAddress: async (patientId, resourceId, patch) => fromAddressDto(await http.patch(`${patientPath(patientId, 'addresses')}/${id(resourceId)}`, addressWrite(patch))),
  listEmergencyContacts: (patientId, signal) => list(http, patientPath(patientId, 'emergency-contacts'), fromEmergencyContactDto, signal), createEmergencyContact: async (patientId, draft) => fromEmergencyContactDto(await http.post(patientPath(patientId, 'emergency-contacts'), contactWrite(draft))), updateEmergencyContact: async (patientId, resourceId, patch) => fromEmergencyContactDto(await http.patch(`${patientPath(patientId, 'emergency-contacts')}/${id(resourceId)}`, contactWrite(patch))),
  listMedicalHistory: (patientId, signal) => list(http, patientPath(patientId, 'medical-history'), fromMedicalHistoryDto, signal), createMedicalHistory: async (patientId, draft) => fromMedicalHistoryDto(await http.post(patientPath(patientId, 'medical-history'), { schema_version: 'v1', answers: { conditions: draft.conditions.map((condition) => condition.trim()).filter(Boolean), smoker: draft.smoker }, summary_notes: nullable(draft.summaryNotes), confirmed_at: nullable(draft.confirmedAt) })),
  listItems: (patientId, kind, signal) => list(http, patientPath(patientId, kind), fromClinicalItemDto, signal), createItem: async (patientId, kind, draft) => fromClinicalItemDto(await http.post(patientPath(patientId, kind), itemWrite(draft))), updateItem: async (patientId, kind, resourceId, patch) => fromClinicalItemDto(await http.patch(`${patientPath(patientId, kind)}/${id(resourceId)}`, itemWrite(patch))),
  listEncounters: (patientId, signal) => list(http, `/api/v1/encounters?patient_id=${id(patientId)}&limit=100`, fromEncounterDto, signal), createEncounter: async (input) => fromEncounterDto(await http.post('/api/v1/encounters', { patient_id: input.patientId, provider_user_id: input.providerUserId, started_at: input.startedAt, ...(input.appointmentId ? { appointment_id: input.appointmentId } : {}) })), getEncounter: async (encounterId, signal) => fromEncounterDto(await http.get(`/api/v1/encounters/${id(encounterId)}`, signal ? { signal } : undefined)), completeEncounter: async (encounterId, version) => fromEncounterDto(await http.post(`/api/v1/encounters/${id(encounterId)}/complete`, { expected_version: version }, { ifMatch: version })), voidEncounter: async (encounterId, version, reason) => fromEncounterDto(await http.post(`/api/v1/encounters/${id(encounterId)}/void`, { expected_version: version, reason: reason.trim() }, { ifMatch: version })),
  listDiagnoses: (encounterId, signal) => list(http, `/api/v1/encounters/${id(encounterId)}/diagnoses`, fromDiagnosisDto, signal), createDiagnosis: async (encounterId, input) => fromDiagnosisDto(await http.post(`/api/v1/encounters/${id(encounterId)}/diagnoses`, { description: input.description.trim(), ...(input.codeSystem ? { code_system: input.codeSystem.trim() } : {}), ...(input.code ? { code: input.code.trim() } : {}), ...(input.toothNumber ? { tooth_number: input.toothNumber } : {}), ...(input.diagnosisType ? { diagnosis_type: input.diagnosisType.trim() } : {}) })),
  listNotes: (encounterId, signal) => list(http, `/api/v1/clinical-notes?encounter_id=${id(encounterId)}`, fromNoteDto, signal), createNote: async (draft) => fromNoteDto(await http.post('/api/v1/clinical-notes', noteWrite(draft))), getNote: async (noteId, signal) => fromNoteDto(await http.get(`/api/v1/clinical-notes/${id(noteId)}`, signal ? { signal } : undefined)), updateNote: async (noteId, version, draft) => fromNoteDto(await http.patch(`/api/v1/clinical-notes/${id(noteId)}`, { ...noteWrite(draft), expected_version: version }, { ifMatch: version })), signNote: async (noteId, version) => fromNoteDto(await http.post(`/api/v1/clinical-notes/${id(noteId)}/sign`, { expected_version: version }, { ifMatch: version })), listAmendments: (noteId, signal) => list(http, `/api/v1/clinical-notes/${id(noteId)}/amendments`, fromAmendmentDto, signal), addAmendment: async (noteId, version, input) => { const result = await http.post<any>(`/api/v1/clinical-notes/${id(noteId)}/amendments`, { expected_version: version, reason: input.reason.trim(), amendment_text: input.amendmentText.trim() }, { ifMatch: version }); return { amendment: fromAmendmentDto(result.amendment), note: fromNoteDto(result.note) } },
  listOdontograms: (patientId, signal) => list(http, `/api/v1/odontograms?patient_id=${id(patientId)}`, fromOdontogramDto, signal), createOdontogram: async (input) => fromOdontogramDto(await http.post('/api/v1/odontograms', { patient_id: input.patientId, ...(input.encounterId ? { encounter_id: input.encounterId } : {}) })), getOdontogram: async (odontogramId, signal) => fromOdontogramDto(await http.get(`/api/v1/odontograms/${id(odontogramId)}`, signal ? { signal } : undefined)), listOdontogramEntries: (odontogramId, signal) => list(http, `/api/v1/odontograms/${id(odontogramId)}/entries`, fromOdontogramEntryDto, signal), createOdontogramEntry: async (odontogramId, version, input) => fromOdontogramEntryDto(await http.post(`/api/v1/odontograms/${id(odontogramId)}/entries`, { tooth_number: input.toothNumber, surface: input.surface, ...(input.conditionCode ? { condition_code: input.conditionCode.trim() } : {}), ...(input.status ? { status: input.status.trim() } : {}), ...(input.notes ? { notes: input.notes.trim() } : {}), expected_version: version }, { ifMatch: version })), signOdontogram: async (odontogramId, version) => fromOdontogramDto(await http.post(`/api/v1/odontograms/${id(odontogramId)}/sign`, { expected_version: version }, { ifMatch: version })),
} }
