import { isApiError } from '../../../shared/api/problem'
export type PrescriptionStatus = 'DRAFT' | 'ISSUED' | 'VOIDED'
export interface Prescription { id: string; patientId: string; encounterId: string; providerUserId: string; status: PrescriptionStatus; instructions: string; issuedAt: string; createdAt: string; updatedAt: string; version: number }
export interface PrescriptionItem { id: string; prescriptionId: string; lineNumber: number; medication: string; presentation: string; dose: string; route: string; frequency: string; duration: string; instructions: string }
const text = (value: unknown) => typeof value === 'string' ? value : ''
export function fromPrescriptionDto(dto: any): Prescription { return { id: dto.id, patientId: dto.patient_id, encounterId: text(dto.encounter_id), providerUserId: dto.provider_user_id, status: dto.status, instructions: text(dto.instructions), issuedAt: text(dto.issued_at), createdAt: dto.created_at, updatedAt: dto.updated_at, version: dto.version } }
export function fromPrescriptionItemDto(dto: any): PrescriptionItem { return { id: dto.id, prescriptionId: dto.prescription_id, lineNumber: dto.line_number, medication: dto.medication, presentation: text(dto.presentation), dose: dto.dose, route: text(dto.route), frequency: dto.frequency, duration: dto.duration, instructions: text(dto.instructions) } }
export const canEditPrescription = (item: Prescription) => item.status === 'DRAFT'
export const canIssuePrescription = (item: Prescription, role: string, userId: string) => item.status === 'DRAFT' && role === 'OWNER_DENTIST' && item.providerUserId === userId
export const canVoidPrescription = (item: Prescription, role: string, userId: string) => (item.status === 'DRAFT' || item.status === 'ISSUED') && role === 'OWNER_DENTIST' && item.providerUserId === userId
export const prescriptionErrorMessage = (error: unknown) => { if (!isApiError(error)) return 'No pudimos completar la receta. Intentá nuevamente.'; if (error.code === 'PRECONDITION_FAILED' || error.code === 'VERSION_CONFLICT' || error.status === 412) return 'La receta cambió en otra sesión. Se conservaron tus datos y recargamos el estado actual.'; if (error.code === 'PRESCRIPTION_REQUIRES_ITEMS') return 'Agregá al menos un medicamento antes de emitir la receta.'; if (error.code === 'INVALID_CLINICAL_TRANSITION') return 'La receta ya es inmutable o no admite ese cambio.'; if (error.code === 'FORBIDDEN') return 'Tu rol no tiene permiso para esta operación.'; return error.detail ?? 'Revisá los datos e intentá nuevamente.' }
export const isPrescriptionConflict = (error: unknown) => isApiError(error) && (error.code === 'PRECONDITION_FAILED' || error.code === 'VERSION_CONFLICT' || error.status === 412)
