import { isApiError } from '../../../shared/api/problem'
export type OrthodonticCaseStatus = 'PLANNED' | 'ACTIVE' | 'RETENTION' | 'COMPLETED' | 'CANCELLED'
export interface OrthodonticCase { id: string; patientId: string; treatmentPlanId: string; providerUserId: string; startedOn: string; estimatedEndOn: string; monthlyFee: string; currency: string; notes: string; status: OrthodonticCaseStatus; completedOn: string; createdAt: string; updatedAt: string; version: number }
export interface OrthodonticVisit { id: string; orthodonticCaseId: string; appointmentId: string; encounterId: string; upperArchwire: string; lowerArchwire: string; elastics: string; procedures: string; observations: string; nextVisitNotes: string; createdBy: string; createdAt: string; updatedAt: string }
const text = (value: unknown) => typeof value === 'string' ? value : ''
export function fromCaseDto(dto: any): OrthodonticCase { return { id: dto.id, patientId: dto.patient_id, treatmentPlanId: text(dto.treatment_plan_id), providerUserId: dto.provider_user_id, startedOn: text(dto.started_on), estimatedEndOn: text(dto.estimated_end_on), monthlyFee: text(dto.monthly_fee), currency: dto.currency, notes: text(dto.notes), status: dto.status, completedOn: text(dto.completed_on), createdAt: dto.created_at, updatedAt: dto.updated_at, version: dto.version } }
export function fromVisitDto(dto: any): OrthodonticVisit { return { id: dto.id, orthodonticCaseId: dto.orthodontic_case_id, appointmentId: text(dto.appointment_id), encounterId: text(dto.encounter_id), upperArchwire: text(dto.upper_archwire), lowerArchwire: text(dto.lower_archwire), elastics: text(dto.elastics), procedures: text(dto.procedures), observations: text(dto.observations), nextVisitNotes: text(dto.next_visit_notes), createdBy: dto.created_by, createdAt: dto.created_at, updatedAt: dto.updated_at } }
const transitions: Record<OrthodonticCaseStatus, OrthodonticCaseStatus[]> = { PLANNED: ['ACTIVE', 'CANCELLED'], ACTIVE: ['RETENTION', 'CANCELLED'], RETENTION: ['COMPLETED', 'CANCELLED'], COMPLETED: [], CANCELLED: [] }
export const allowedCaseTransitions = (status: OrthodonticCaseStatus) => transitions[status]
export const orthodonticsErrorMessage = (error: unknown) => { if (!isApiError(error)) return 'No pudimos completar el caso de ortodoncia. Intentá nuevamente.'; if (error.code === 'PRECONDITION_FAILED' || error.code === 'VERSION_CONFLICT' || error.status === 412) return 'El caso cambió en otra sesión. Se conservaron tus datos y recargamos el estado actual.'; if (error.code === 'INVALID_ORTHODONTIC_TRANSITION') return 'Ese cambio no está permitido en el estado actual del caso.'; if (error.code === 'FORBIDDEN') return 'Tu rol no tiene permiso para esta operación.'; return error.detail ?? 'Revisá los datos e intentá nuevamente.' }
export const isOrthodonticsConflict = (error: unknown) => isApiError(error) && (error.code === 'PRECONDITION_FAILED' || error.code === 'VERSION_CONFLICT' || error.status === 412)
