import { useState } from 'react'
import { useResource } from '../../../../shared/api/useResource'
import { Badge } from '../../../../shared/ui/atoms/Badge'
import { Button } from '../../../../shared/ui/atoms/Button'
import { SelectField, TextArea, TextField } from '../../../../shared/ui/atoms/Field'
import type { ClinicalApi } from '../../application/clinicalApi'
import type { Address, AddressDraft, ClinicalItem, ClinicalItemDraft, ClinicalItemKind, EmergencyContact, EmergencyContactDraft, MedicalHistoryDraft } from '../../domain/clinical'
import styles from '../ClinicalRecordTabs.module.css'
import { InlineForm, isResourceReady, List, LoadingError } from './common'

const emptyItem = (): ClinicalItemDraft => ({ name: '', codeSystem: '', code: '', reaction: '', severity: '', dose: '', frequency: '', diagnosedOn: '', startedOn: '', endedOn: '', isActive: true, notes: '' })
const itemFrom = (item: ClinicalItem): ClinicalItemDraft => ({ name: item.name, codeSystem: item.codeSystem, code: item.code, reaction: item.reaction, severity: item.severity, dose: item.dose, frequency: item.frequency, diagnosedOn: item.diagnosedOn, startedOn: item.startedOn, endedOn: item.endedOn, isActive: item.isActive, notes: item.notes })

export function ClinicalSummaryTab({ api, patientId }: { api: ClinicalApi; patientId: string }) {
  const addresses = useResource((signal) => api.listAddresses(patientId, signal), [api, patientId])
  const contacts = useResource((signal) => api.listEmergencyContacts(patientId, signal), [api, patientId])
  return <section className={styles.stack} aria-label="Resumen clínico"><h3>Antecedentes clínicos</h3><AddressPanel api={api} patientId={patientId} resource={addresses} /><ContactPanel api={api} patientId={patientId} resource={contacts} /></section>
}

function AddressPanel({ api, patientId, resource }: { api: ClinicalApi; patientId: string; resource: ReturnType<typeof useResource<Address[]>> }) {
  const [editing, setEditing] = useState<Address | null>(null); const [creating, setCreating] = useState(false); const ready = isResourceReady(resource)
  return <article className={styles.card}><div className={styles.heading}><h4>Direcciones</h4><Button size="sm" disabled={!ready} onClick={() => setCreating(true)}>Agregar dirección</Button></div><LoadingError resource={resource}>{(items, reload, listReady) => <><List items={items} empty="No hay direcciones registradas." render={(item) => <div><strong>{item.addressType}</strong>{item.isPrimary ? <Badge tone="ok">Principal</Badge> : null}<p>{[item.street, item.exteriorNumber, item.interiorNumber, item.neighborhood, item.municipality, item.state, item.postalCode, item.countryCode].filter(Boolean).join(', ') || 'Sin detalle de domicilio'}</p><Button variant="secondary" size="sm" disabled={!listReady} onClick={() => setEditing(item)}>Editar</Button></div>} />{creating ? <AddressForm disabled={!listReady} onCancel={() => setCreating(false)} onSave={async (draft) => { await api.createAddress(patientId, draft); setCreating(false); await reload() }} /> : null}{editing ? <AddressForm initial={editing} disabled={!listReady} onCancel={() => setEditing(null)} onSave={async (draft) => { await api.updateAddress(patientId, editing.id, draft); setEditing(null); await reload() }} /> : null}</>}</LoadingError></article>
}
function AddressForm({ initial, disabled, onCancel, onSave }: { initial?: Address; disabled: boolean; onCancel: () => void; onSave: (draft: AddressDraft) => Promise<void> }) {
  const [draft, setDraft] = useState<AddressDraft>(() => initial ? { addressType: initial.addressType, street: initial.street, exteriorNumber: initial.exteriorNumber, interiorNumber: initial.interiorNumber, neighborhood: initial.neighborhood, municipality: initial.municipality, state: initial.state, postalCode: initial.postalCode, countryCode: initial.countryCode, isPrimary: initial.isPrimary } : { addressType: 'HOME', street: '', exteriorNumber: '', interiorNumber: '', neighborhood: '', municipality: '', state: '', postalCode: '', countryCode: 'MX', isPrimary: false })
  return <InlineForm title={initial ? 'Editar dirección' : 'Nueva dirección'} disabled={disabled} onCancel={onCancel} onSave={() => onSave(draft)}><div className={styles.columns}><SelectField label="Tipo" value={draft.addressType} options={['HOME', 'CONTACT', 'OTHER']} onChange={(event) => setDraft({ ...draft, addressType: event.target.value as AddressDraft['addressType'] })} /><TextField label="Calle" value={draft.street} onChange={(event) => setDraft({ ...draft, street: event.target.value })} /><TextField label="Número exterior" value={draft.exteriorNumber} onChange={(event) => setDraft({ ...draft, exteriorNumber: event.target.value })} /><TextField label="Número interior" value={draft.interiorNumber} onChange={(event) => setDraft({ ...draft, interiorNumber: event.target.value })} /><TextField label="Colonia" value={draft.neighborhood} onChange={(event) => setDraft({ ...draft, neighborhood: event.target.value })} /><TextField label="Municipio" value={draft.municipality} onChange={(event) => setDraft({ ...draft, municipality: event.target.value })} /><TextField label="Estado" value={draft.state} onChange={(event) => setDraft({ ...draft, state: event.target.value })} /><TextField label="Código postal" value={draft.postalCode} onChange={(event) => setDraft({ ...draft, postalCode: event.target.value })} /><TextField label="País (ISO)" value={draft.countryCode} onChange={(event) => setDraft({ ...draft, countryCode: event.target.value })} /></div><label className={styles.check}><input type="checkbox" checked={draft.isPrimary} onChange={(event) => setDraft({ ...draft, isPrimary: event.target.checked })} /> Dirección principal</label></InlineForm>
}
function ContactPanel({ api, patientId, resource }: { api: ClinicalApi; patientId: string; resource: ReturnType<typeof useResource<EmergencyContact[]>> }) {
  const [editing, setEditing] = useState<EmergencyContact | null>(null); const [creating, setCreating] = useState(false); const ready = isResourceReady(resource)
  return <article className={styles.card}><div className={styles.heading}><h4>Contactos de emergencia</h4><Button size="sm" disabled={!ready} onClick={() => setCreating(true)}>Agregar contacto</Button></div><LoadingError resource={resource}>{(items, reload, listReady) => <><List items={items} empty="No hay contactos de emergencia registrados." render={(item) => <div><strong>{item.name}</strong>{item.isPrimary ? <Badge tone="ok">Principal</Badge> : null}<p>{[item.relationship, item.phoneE164].filter(Boolean).join(' · ')}</p><Button variant="secondary" size="sm" disabled={!listReady} onClick={() => setEditing(item)}>Editar</Button></div>} />{creating ? <ContactForm disabled={!listReady} onCancel={() => setCreating(false)} onSave={async (draft) => { await api.createEmergencyContact(patientId, draft); setCreating(false); await reload() }} /> : null}{editing ? <ContactForm initial={editing} disabled={!listReady} onCancel={() => setEditing(null)} onSave={async (draft) => { await api.updateEmergencyContact(patientId, editing.id, draft); setEditing(null); await reload() }} /> : null}</>}</LoadingError></article>
}
function ContactForm({ initial, disabled, onCancel, onSave }: { initial?: EmergencyContact; disabled: boolean; onCancel: () => void; onSave: (draft: EmergencyContactDraft) => Promise<void> }) { const [draft, setDraft] = useState<EmergencyContactDraft>(() => initial ? { name: initial.name, relationship: initial.relationship, phoneE164: initial.phoneE164, isPrimary: initial.isPrimary } : { name: '', relationship: '', phoneE164: '', isPrimary: false }); return <InlineForm title={initial ? 'Editar contacto' : 'Nuevo contacto'} disabled={disabled} onCancel={onCancel} onSave={() => onSave(draft)}><div className={styles.columns}><TextField label="Nombre" required value={draft.name} onChange={(event) => setDraft({ ...draft, name: event.target.value })} /><TextField label="Parentesco" value={draft.relationship} onChange={(event) => setDraft({ ...draft, relationship: event.target.value })} /><TextField label="Teléfono" required value={draft.phoneE164} onChange={(event) => setDraft({ ...draft, phoneE164: event.target.value })} /></div><label className={styles.check}><input type="checkbox" checked={draft.isPrimary} onChange={(event) => setDraft({ ...draft, isPrimary: event.target.checked })} /> Contacto principal</label></InlineForm> }

export function MedicalHistoryTab({ api, patientId }: { api: ClinicalApi; patientId: string }) { const resource = useResource((signal) => api.listMedicalHistory(patientId, signal), [api, patientId]); const [creating, setCreating] = useState(false); const ready = isResourceReady(resource); return <section className={styles.stack} aria-label="Historial médico"><div className={styles.heading}><h3>Historial médico</h3><Button size="sm" disabled={!ready} onClick={() => setCreating(true)}>Registrar nueva versión</Button></div><LoadingError resource={resource}>{(items, reload, listReady) => <><List items={items} empty="No hay antecedentes médicos registrados." render={(item) => <div><strong>Versión {item.versionNumber}</strong><p>Condiciones: {item.answers.conditions.join(', ') || 'Ninguna registrada'}</p></div>} />{creating ? <HistoryForm disabled={!listReady} onCancel={() => setCreating(false)} onSave={async (draft) => { await api.createMedicalHistory(patientId, draft); setCreating(false); await reload() }} /> : null}</>}</LoadingError></section> }
function HistoryForm({ disabled, onCancel, onSave }: { disabled: boolean; onCancel: () => void; onSave: (draft: MedicalHistoryDraft) => Promise<void> }) { const [conditions, setConditions] = useState(''); const [smoker, setSmoker] = useState(false); const [summaryNotes, setSummaryNotes] = useState(''); const [confirmedAt, setConfirmedAt] = useState(''); return <InlineForm title="Nueva versión de antecedentes" disabled={disabled} onCancel={onCancel} onSave={() => onSave({ conditions: conditions.split(',').map((value) => value.trim()).filter(Boolean), smoker, summaryNotes, confirmedAt: confirmedAt ? new Date(confirmedAt).toISOString() : '' })}><TextField label="Condiciones separadas por comas" value={conditions} onChange={(event) => setConditions(event.target.value)} /><label className={styles.check}><input type="checkbox" checked={smoker} onChange={(event) => setSmoker(event.target.checked)} /> La persona refiere consumo de tabaco</label><TextArea label="Resumen clínico" rows={3} value={summaryNotes} onChange={(event) => setSummaryNotes(event.target.value)} /><TextField label="Confirmado el" type="datetime-local" value={confirmedAt} onChange={(event) => setConfirmedAt(event.target.value)} /></InlineForm> }

export function ItemCollection({ api, patientId, kind, title }: { api: ClinicalApi; patientId: string; kind: ClinicalItemKind; title: string }) { const resource = useResource((signal) => api.listItems(patientId, kind, signal), [api, patientId, kind]); const [editing, setEditing] = useState<ClinicalItem | null>(null); const [creating, setCreating] = useState(false); const ready = isResourceReady(resource); return <article className={styles.card}><div className={styles.heading}><h4>{title}</h4><Button size="sm" disabled={!ready} onClick={() => setCreating(true)}>Agregar</Button></div><LoadingError resource={resource}>{(items, reload, listReady) => <><List items={items} empty={`No hay ${title.toLowerCase()} registrados.`} render={(item) => <div><strong>{item.name}</strong><p>{item.notes || 'Sin detalles adicionales'}</p><Button variant="secondary" size="sm" disabled={!listReady} onClick={() => setEditing(item)}>Editar</Button></div>} />{creating ? <ItemForm disabled={!listReady} onCancel={() => setCreating(false)} onSave={async (draft) => { await api.createItem(patientId, kind, draft); setCreating(false); await reload() }} /> : null}{editing ? <ItemForm initial={editing} disabled={!listReady} onCancel={() => setEditing(null)} onSave={async (draft) => { await api.updateItem(patientId, kind, editing.id, draft); setEditing(null); await reload() }} /> : null}</>}</LoadingError></article> }
function ItemForm({ initial, disabled, onCancel, onSave }: { initial?: ClinicalItem; disabled: boolean; onCancel: () => void; onSave: (draft: ClinicalItemDraft) => Promise<void> }) { const [draft, setDraft] = useState(() => initial ? itemFrom(initial) : emptyItem()); return <InlineForm title={initial ? 'Editar registro clínico' : 'Nuevo registro clínico'} disabled={disabled} onCancel={onCancel} onSave={() => onSave(draft)}><TextField label="Nombre" required value={draft.name} onChange={(event) => setDraft({ ...draft, name: event.target.value })} /><TextArea label="Notas" rows={2} value={draft.notes} onChange={(event) => setDraft({ ...draft, notes: event.target.value })} /></InlineForm> }
