import { useState } from 'react'
import { useResource } from '../../../../shared/api/useResource'
import { Button } from '../../../../shared/ui/atoms/Button'
import { TextArea, TextField } from '../../../../shared/ui/atoms/Field'
import { FormAlert } from '../../../../shared/ui/molecules/FormAlert'
import type { ClinicalApi } from '../../application/clinicalApi'
import { clinicalErrorMessage, isClinicalVersionConflict, type ClinicalEncounter, type EncounterDiagnosis } from '../../domain/clinical'
import styles from '../ClinicalRecordTabs.module.css'
import { InlineForm, isResourceReady, List, LoadingError, useActionGuard } from './common'

export function EncounterPanel({ api, patientId, userId, owner, resource }: { api: ClinicalApi; patientId: string; userId: string; owner: boolean; resource: ReturnType<typeof useResource<ClinicalEncounter[]>> }) {
  const [creating, setCreating] = useState(false); const [selected, setSelected] = useState('')
  const ready = isResourceReady(resource)
  return <article className={styles.card}><div className={styles.heading}><div><h4>Atenciones</h4><p>Las atenciones completadas o anuladas no se pueden modificar.</p></div>{owner ? <Button size="sm" disabled={!ready} onClick={() => setCreating(true)}>Abrir atención</Button> : null}</div><LoadingError resource={resource}>{(items, reload, listReady) => <><List items={items} empty="No hay atenciones clínicas." render={(item) => <button type="button" className={styles.rowButton} onClick={() => setSelected(item.id)}><strong>{item.status === 'OPEN' ? 'Atención abierta' : item.status === 'COMPLETED' ? 'Atención completada' : 'Atención anulada'}</strong><span>{item.startedAt}</span></button>} />{creating ? <EncounterForm disabled={!listReady} onCancel={() => setCreating(false)} onSave={async (startedAt) => { await api.createEncounter({ patientId, providerUserId: userId, startedAt: new Date(startedAt).toISOString() }); setCreating(false); await reload() }} /> : null}{selected ? <EncounterDetail api={api} encounterId={selected} userId={userId} owner={owner} listReady={listReady} onChanged={reload} /> : null}</>}</LoadingError></article>
}
function EncounterForm({ disabled, onCancel, onSave }: { disabled: boolean; onCancel: () => void; onSave: (startedAt: string) => Promise<void> }) { const [startedAt, setStartedAt] = useState(''); return <InlineForm title="Abrir atención clínica" disabled={disabled} onCancel={onCancel} onSave={() => onSave(startedAt)}><TextField label="Inicio de la atención" type="datetime-local" required value={startedAt} onChange={(event) => setStartedAt(event.target.value)} /></InlineForm> }

export function EncounterDetail({ api, encounterId, userId, owner, listReady, onChanged }: { api: ClinicalApi; encounterId: string; userId: string; owner: boolean; listReady: boolean; onChanged: () => Promise<void> }) {
  const resource = useResource((signal) => api.getEncounter(encounterId, signal), [api, encounterId])
  const [mutationError, setMutationError] = useState<string | null>(null)
  return <div className={styles.detail}>{mutationError ? <FormAlert tone="error">{mutationError}</FormAlert> : null}<LoadingError resource={resource}>{(encounter, reload, detailReady) => {
    const ownsEncounter = owner && encounter.providerUserId === userId
    const canWrite = detailReady && listReady
    const refresh = async () => { await reload(); await onChanged() }
    return <><h5>Detalle de atención</h5><p>Estado: <strong>{encounter.status}</strong> · Versión {encounter.version}</p>{encounter.status === 'OPEN' && ownsEncounter ? <EncounterActions api={api} encounter={encounter} enabled={canWrite} reload={refresh} onError={setMutationError} /> : null}<DiagnosisPanel api={api} encounterId={encounter.id} editable={encounter.status === 'OPEN' && ownsEncounter} parentReady={canWrite} /></>
  }}</LoadingError></div>
}
function EncounterActions({ api, encounter, enabled, reload, onError }: { api: ClinicalApi; encounter: ClinicalEncounter; enabled: boolean; reload: () => Promise<void>; onError: (message: string) => void }) {
  const [mode, setMode] = useState<'complete' | 'void' | null>(null); const [reason, setReason] = useState(''); const { pending, run: act } = useActionGuard()
  const submit = () => act(async () => { try { if (mode === 'complete') await api.completeEncounter(encounter.id, encounter.version); if (mode === 'void') await api.voidEncounter(encounter.id, encounter.version, reason); setMode(null); await reload() } catch (error) { onError(clinicalErrorMessage(error)); if (isClinicalVersionConflict(error)) await reload() } }, enabled)
  return <div className={styles.actions}>{mode ? <div className={styles.confirm} role="alertdialog" aria-label="Confirmar transición de atención">{mode === 'void' ? <TextArea label="Motivo de anulación" required value={reason} onChange={(event) => setReason(event.target.value)} /> : <p>¿Confirmás completar esta atención? La transición es inmutable.</p>}<Button variant="secondary" size="sm" disabled={pending} onClick={() => setMode(null)}>Cancelar</Button><Button size="sm" onClick={() => void submit()} disabled={!enabled || pending || (mode === 'void' && !reason.trim())}>{pending ? 'Guardando…' : `Confirmar ${mode === 'complete' ? 'finalización' : 'anulación'}`}</Button></div> : <><Button variant="secondary" size="sm" disabled={!enabled} onClick={() => setMode('void')}>Anular</Button><Button size="sm" disabled={!enabled} onClick={() => setMode('complete')}>Completar</Button></>}</div>
}
function DiagnosisPanel({ api, encounterId, editable, parentReady }: { api: ClinicalApi; encounterId: string; editable: boolean; parentReady: boolean }) { const resource = useResource((signal) => api.listDiagnoses(encounterId, signal), [api, encounterId]); const [creating, setCreating] = useState(false); const ready = isResourceReady(resource); return <div className={styles.nested}><div className={styles.heading}><h5>Diagnósticos</h5>{editable ? <Button size="sm" variant="secondary" disabled={!parentReady || !ready} onClick={() => setCreating(true)}>Agregar diagnóstico</Button> : null}</div><LoadingError resource={resource}>{(items, reload, listReady) => <><List items={items} empty="Sin diagnósticos registrados." render={(item: EncounterDiagnosis) => <div><strong>{item.description}</strong><p>{[item.codeSystem, item.code, item.diagnosisType, item.toothNumber ? `Pieza ${item.toothNumber}` : ''].filter(Boolean).join(' · ')}</p></div>} />{creating ? <DiagnosisForm disabled={!parentReady || !listReady} onCancel={() => setCreating(false)} onSave={async (input) => { await api.createDiagnosis(encounterId, input); setCreating(false); await reload() }} /> : null}</>}</LoadingError></div> }
function DiagnosisForm({ disabled, onCancel, onSave }: { disabled: boolean; onCancel: () => void; onSave: (input: { description: string; codeSystem: string; code: string; toothNumber?: number; diagnosisType: string }) => Promise<void> }) { const [description, setDescription] = useState(''); const [codeSystem, setCodeSystem] = useState(''); const [code, setCode] = useState(''); const [tooth, setTooth] = useState(''); const [diagnosisType, setDiagnosisType] = useState(''); return <InlineForm title="Nuevo diagnóstico" disabled={disabled} onCancel={onCancel} onSave={() => onSave({ description, codeSystem, code, toothNumber: tooth ? Number(tooth) : undefined, diagnosisType })}><div className={styles.columns}><TextField label="Descripción" required value={description} onChange={(event) => setDescription(event.target.value)} /><TextField label="Sistema de código" value={codeSystem} onChange={(event) => setCodeSystem(event.target.value)} /><TextField label="Código" value={code} onChange={(event) => setCode(event.target.value)} /><TextField label="Pieza dental FDI" inputMode="numeric" value={tooth} onChange={(event) => setTooth(event.target.value)} /><TextField label="Tipo de diagnóstico" value={diagnosisType} onChange={(event) => setDiagnosisType(event.target.value)} /></div></InlineForm> }
