import { useState } from 'react'
import { useResource } from '../../../../shared/api/useResource'
import { Badge } from '../../../../shared/ui/atoms/Badge'
import { Button } from '../../../../shared/ui/atoms/Button'
import { SelectField, TextArea, TextField } from '../../../../shared/ui/atoms/Field'
import { FormAlert } from '../../../../shared/ui/molecules/FormAlert'
import type { ClinicalApi } from '../../application/clinicalApi'
import { clinicalErrorMessage, isClinicalVersionConflict, type ClinicalNote, type ClinicalNoteAmendment, type ClinicalNoteDraft } from '../../domain/clinical'
import styles from '../ClinicalRecordTabs.module.css'
import { InlineForm, isResourceReady, List, LoadingError, useActionGuard } from './common'

export function NotesTab({ api, patientId, userId, owner }: { api: ClinicalApi; patientId: string; userId: string; owner: boolean }) {
  const encounters = useResource((signal) => api.listEncounters(patientId, signal), [api, patientId]); const [encounterId, setEncounterId] = useState('')
  return <section className={styles.stack} aria-label="Notas clínicas"><h3>Notas clínicas</h3><LoadingError resource={encounters}>{(items, _reload, encountersReady) => <>{items.length ? <SelectField label="Atención" value={encounterId} options={[{ value: '', label: 'Seleccioná una atención' }, ...items.map((item) => ({ value: item.id, label: `${item.status} · ${item.startedAt}` }))]} onChange={(event) => setEncounterId(event.target.value)} /> : <p>No hay atenciones disponibles para registrar notas.</p>}{encounterId ? <NotesForEncounter key={encounterId} api={api} encounterId={encounterId} encounterListReady={encountersReady} userId={userId} owner={owner} /> : null}</>}</LoadingError></section>
}
function NotesForEncounter({ api, encounterId, encounterListReady, userId, owner }: { api: ClinicalApi; encounterId: string; encounterListReady: boolean; userId: string; owner: boolean }) {
  const resource = useResource((signal) => api.listNotes(encounterId, signal), [api, encounterId]); const [creating, setCreating] = useState(false); const [selected, setSelected] = useState(''); const ready = isResourceReady(resource)
  return <article className={styles.card}><div className={styles.heading}><h4>Notas de la atención</h4><Button size="sm" disabled={!encounterListReady || !ready} onClick={() => setCreating(true)}>Crear borrador</Button></div><LoadingError resource={resource}>{(items, reload, listReady) => <><List items={items} empty="No hay notas clínicas." render={(item) => <button type="button" className={styles.rowButton} onClick={() => setSelected(item.id)}><strong>{item.noteType}</strong><span>{item.status} · versión {item.version}</span></button>} />{creating ? <NoteForm disabled={!encounterListReady || !listReady} onCancel={() => setCreating(false)} onSave={async (draft) => { await api.createNote({ ...draft, encounterId }); setCreating(false); await reload() }} /> : null}{selected ? <NoteDetail key={selected} api={api} noteId={selected} encounterListReady={encounterListReady} listReady={listReady} userId={userId} owner={owner} onChanged={reload} /> : null}</>}</LoadingError></article>
}
function NoteForm({ initial, disabled, onCancel, onSave }: { initial?: ClinicalNote; disabled: boolean; onCancel: () => void; onSave: (draft: ClinicalNoteDraft) => Promise<void> }) { const [draft, setDraft] = useState<ClinicalNoteDraft>(() => initial ? { noteType: initial.noteType, subjective: initial.subjective, objective: initial.objective, assessment: initial.assessment, plan: initial.plan, additionalNotes: initial.additionalNotes } : { noteType: '', subjective: '', objective: '', assessment: '', plan: '', additionalNotes: '' }); return <InlineForm title={initial ? 'Editar borrador' : 'Nuevo borrador'} disabled={disabled} onCancel={onCancel} onSave={() => onSave(draft)}><TextField label="Tipo de nota" required value={draft.noteType} onChange={(event) => setDraft({ ...draft, noteType: event.target.value })} /><div className={styles.columns}><TextArea label="Subjetivo" rows={3} value={draft.subjective} onChange={(event) => setDraft({ ...draft, subjective: event.target.value })} /><TextArea label="Objetivo" rows={3} value={draft.objective} onChange={(event) => setDraft({ ...draft, objective: event.target.value })} /><TextArea label="Evaluación" rows={3} value={draft.assessment} onChange={(event) => setDraft({ ...draft, assessment: event.target.value })} /><TextArea label="Plan" rows={3} value={draft.plan} onChange={(event) => setDraft({ ...draft, plan: event.target.value })} /></div><TextArea label="Notas adicionales" rows={3} value={draft.additionalNotes} onChange={(event) => setDraft({ ...draft, additionalNotes: event.target.value })} /></InlineForm> }
function NoteDetail({ api, noteId, encounterListReady, listReady, userId, owner, onChanged }: { api: ClinicalApi; noteId: string; encounterListReady: boolean; listReady: boolean; userId: string; owner: boolean; onChanged: () => Promise<void> }) {
  const resource = useResource((signal) => api.getNote(noteId, signal), [api, noteId]); const [editing, setEditing] = useState(false); const [signing, setSigning] = useState(false); const [mutationError, setMutationError] = useState<string | null>(null); const { pending, run: act } = useActionGuard()
  return <div className={styles.detail}>{mutationError ? <FormAlert tone="error">{mutationError}</FormAlert> : null}<LoadingError resource={resource}>{(note, reload, detailReady) => {
    const providerOwnsNote = owner && note.providerUserId === userId
    const canWrite = encounterListReady && listReady && detailReady
    const canEditDraft = note.status === 'DRAFT' && (!owner || note.providerUserId === userId)
    const refresh = async () => { await reload(); await onChanged() }
    const sign = () => act(async () => { try { await api.signNote(note.id, note.version); setSigning(false); await refresh() } catch (error) { setMutationError(clinicalErrorMessage(error)); if (isClinicalVersionConflict(error)) await refresh() } }, canWrite)
    return <><h5>Detalle de nota</h5><p><Badge tone="neutral">{note.status}</Badge> Versión {note.version}</p><p>Las notas firmadas son inmutables y sus cambios se registran como enmiendas.</p><dl className={styles.note}><div><dt>Subjetivo</dt><dd>{note.subjective || 'Sin contenido'}</dd></div><div><dt>Objetivo</dt><dd>{note.objective || 'Sin contenido'}</dd></div><div><dt>Evaluación</dt><dd>{note.assessment || 'Sin contenido'}</dd></div><div><dt>Plan</dt><dd>{note.plan || 'Sin contenido'}</dd></div></dl>{editing ? <NoteForm initial={note} disabled={!canWrite} onCancel={() => setEditing(false)} onSave={async (draft) => { try { await api.updateNote(note.id, note.version, draft); setEditing(false); await refresh() } catch (error) { if (isClinicalVersionConflict(error)) await refresh(); throw error } }} /> : null}{note.status === 'DRAFT' ? <div className={styles.actions}>{canEditDraft ? <Button variant="secondary" size="sm" disabled={!canWrite} onClick={() => setEditing(true)}>Editar borrador</Button> : null}{providerOwnsNote ? signing ? <div className={styles.confirm} role="alertdialog" aria-label="Confirmar firma de nota"><p>¿Confirmás firmar? El contenido clínico quedará inmutable.</p><Button variant="secondary" size="sm" disabled={pending} onClick={() => setSigning(false)}>Cancelar</Button><Button size="sm" disabled={!canWrite || pending} onClick={() => void sign()}>{pending ? 'Firmando…' : 'Confirmar firma'}</Button></div> : <Button size="sm" disabled={!canWrite} onClick={() => setSigning(true)}>Firmar nota</Button> : null}</div> : <Amendments api={api} note={note} canAmend={providerOwnsNote} parentReady={canWrite} reload={refresh} />}</>
  }}</LoadingError></div>
}
function Amendments({ api, note, canAmend, parentReady, reload }: { api: ClinicalApi; note: ClinicalNote; canAmend: boolean; parentReady: boolean; reload: () => Promise<void> }) { const resource = useResource((signal) => api.listAmendments(note.id, signal), [api, note.id]); const [creating, setCreating] = useState(false); const [reason, setReason] = useState(''); const [text, setText] = useState(''); const ready = isResourceReady(resource); const canWrite = canAmend && parentReady && ready; return <div className={styles.nested}><div className={styles.heading}><h5>Enmiendas</h5>{canAmend ? <Button size="sm" variant="secondary" disabled={!canWrite} onClick={() => setCreating(true)}>Agregar enmienda</Button> : null}</div><LoadingError resource={resource}>{(items, refresh, amendmentsReady) => <><List items={items} empty="No hay enmiendas." render={(item: ClinicalNoteAmendment) => <div><strong>{item.reason}</strong><p>{item.amendmentText}</p></div>} />{creating ? <InlineForm title="Nueva enmienda" disabled={!canAmend || !parentReady || !amendmentsReady} onCancel={() => setCreating(false)} onSave={async () => { await api.addAmendment(note.id, note.version, { reason, amendmentText: text }); setCreating(false); await refresh(); await reload() }}><TextField label="Motivo" required value={reason} onChange={(event) => setReason(event.target.value)} /><TextArea label="Texto de la enmienda" required rows={3} value={text} onChange={(event) => setText(event.target.value)} /></InlineForm> : null}</>}</LoadingError></div> }
