import { useState } from 'react'
import { useResource } from '../../../../shared/api/useResource'
import { Badge } from '../../../../shared/ui/atoms/Badge'
import { Button } from '../../../../shared/ui/atoms/Button'
import { SelectField, TextArea, TextField } from '../../../../shared/ui/atoms/Field'
import { FormAlert } from '../../../../shared/ui/molecules/FormAlert'
import type { ClinicalApi } from '../../application/clinicalApi'
import { clinicalErrorMessage, isClinicalVersionConflict, type ClinicalEncounter, type Odontogram, type OdontogramEntry, type ToothSurface } from '../../domain/clinical'
import styles from '../ClinicalRecordTabs.module.css'
import { InlineForm, isResourceReady, List, LoadingError, useActionGuard } from './common'

export function OdontogramTab({ api, patientId, owner }: { api: ClinicalApi; patientId: string; owner: boolean }) {
  const resource = useResource((signal) => api.listOdontograms(patientId, signal), [api, patientId]); const encounters = useResource((signal) => api.listEncounters(patientId, signal), [api, patientId]); const [creating, setCreating] = useState(false); const [selected, setSelected] = useState(''); const ready = isResourceReady(resource)
  return <section className={styles.stack} aria-label="Odontograma"><div className={styles.heading}><div><h3>Odontograma</h3><p>Las versiones firmadas son inmutables.</p></div><Button size="sm" disabled={!ready} onClick={() => setCreating(true)}>Nueva versión</Button></div><LoadingError resource={resource}>{(items, reload, listReady) => <><List items={items} empty="No hay odontogramas registrados." render={(item) => <button type="button" className={styles.rowButton} onClick={() => setSelected(item.id)}><strong>Versión {item.versionNumber}</strong><span>{item.status} · versión {item.version}</span></button>} />{creating ? <LoadingError resource={encounters}>{(encounterItems, _reload, encountersReady) => <OdontogramForm encounters={encounterItems} disabled={!listReady || !encountersReady} onCancel={() => setCreating(false)} onSave={async (encounterId) => { await api.createOdontogram({ patientId, encounterId: encounterId || undefined }); setCreating(false); await reload() }} />}</LoadingError> : null}{selected ? <OdontogramDetail key={selected} api={api} odontogramId={selected} listReady={listReady} owner={owner} onChanged={reload} /> : null}</>}</LoadingError></section>
}
function OdontogramForm({ encounters, disabled, onCancel, onSave }: { encounters: ClinicalEncounter[]; disabled: boolean; onCancel: () => void; onSave: (encounterId: string) => Promise<void> }) { const [encounterId, setEncounterId] = useState(''); return <InlineForm title="Nueva versión de odontograma" disabled={disabled} onCancel={onCancel} onSave={() => onSave(encounterId)}><SelectField label="Atención vinculada (opcional)" value={encounterId} options={[{ value: '', label: 'Sin atención vinculada' }, ...encounters.map((encounter) => ({ value: encounter.id, label: `${encounter.status} · ${encounter.startedAt}` }))]} onChange={(event) => setEncounterId(event.target.value)} /></InlineForm> }
function OdontogramDetail({ api, odontogramId, listReady, owner, onChanged }: { api: ClinicalApi; odontogramId: string; listReady: boolean; owner: boolean; onChanged: () => Promise<void> }) { const resource = useResource((signal) => api.getOdontogram(odontogramId, signal), [api, odontogramId]); const [error, setError] = useState<string | null>(null); return <div className={styles.detail}>{error ? <FormAlert tone="error">{error}</FormAlert> : null}<LoadingError resource={resource}>{(odontogram, reload, detailReady) => <><h5>Detalle de odontograma</h5><p><Badge tone="neutral">{odontogram.status}</Badge> Versión {odontogram.version}</p>{odontogram.status !== 'DRAFT' ? <p>Este odontograma está firmado o fue sustituido; sus entradas se conservan para consulta y no se pueden modificar.</p> : null}<OdontogramEntries api={api} odontogram={odontogram} editable={odontogram.status === 'DRAFT'} canSign={owner && odontogram.status === 'DRAFT'} parentReady={listReady && detailReady} reload={async () => { await reload(); await onChanged() }} onError={setError} /></>}</LoadingError></div> }
function OdontogramEntries({ api, odontogram, editable, canSign, parentReady, reload, onError }: { api: ClinicalApi; odontogram: Odontogram; editable: boolean; canSign: boolean; parentReady: boolean; reload: () => Promise<void>; onError: (message: string) => void }) { const resource = useResource((signal) => api.listOdontogramEntries(odontogram.id, signal), [api, odontogram.id]); const [creating, setCreating] = useState(false); const [signing, setSigning] = useState(false); const { pending, run: act } = useActionGuard(); const ready = isResourceReady(resource); const canWrite = parentReady && ready; const sign = () => act(async () => { try { await api.signOdontogram(odontogram.id, odontogram.version); setSigning(false); await reload() } catch (error) { onError(clinicalErrorMessage(error)); if (isClinicalVersionConflict(error)) await reload() } }, canWrite); return <div className={styles.nested}><div className={styles.heading}><h5>Entradas</h5>{editable ? <Button size="sm" variant="secondary" disabled={!canWrite} onClick={() => setCreating(true)}>Agregar entrada</Button> : null}</div><LoadingError resource={resource}>{(items, refresh, entriesReady) => <><List items={items} empty="No hay entradas registradas." render={(item: OdontogramEntry) => <div><strong>Pieza {item.toothNumber} · {item.surface}</strong><p>{[item.conditionCode, item.status, item.notes].filter(Boolean).join(' · ') || 'Sin detalle adicional'}</p></div>} />{creating && editable ? <OdontogramEntryForm disabled={!parentReady || !entriesReady} onCancel={() => setCreating(false)} onSave={async (input) => { await api.createOdontogramEntry(odontogram.id, odontogram.version, input); setCreating(false); await refresh(); await reload() }} /> : null}{canSign ? signing ? <div className={styles.confirm} role="alertdialog" aria-label="Confirmar firma de odontograma"><p>¿Confirmás firmar este odontograma? Sus entradas quedarán inmutables.</p><Button variant="secondary" size="sm" disabled={pending} onClick={() => setSigning(false)}>Cancelar</Button><Button size="sm" disabled={!parentReady || !entriesReady || pending} onClick={() => void sign()}>{pending ? 'Firmando…' : 'Confirmar firma'}</Button></div> : <Button size="sm" disabled={!canWrite} onClick={() => setSigning(true)}>Firmar odontograma</Button> : null}</>}</LoadingError></div> }
function OdontogramEntryForm({ disabled, onCancel, onSave }: { disabled: boolean; onCancel: () => void; onSave: (input: { toothNumber: number; surface: ToothSurface; conditionCode: string; status: string; notes: string }) => Promise<void> }) { const [toothNumber, setToothNumber] = useState(''); const [surface, setSurface] = useState<ToothSurface>('GENERAL'); const [conditionCode, setConditionCode] = useState(''); const [status, setStatus] = useState(''); const [notes, setNotes] = useState(''); return <InlineForm title="Nueva entrada odontológica" disabled={disabled} onCancel={onCancel} onSave={() => onSave({ toothNumber: Number(toothNumber), surface, conditionCode, status, notes })}><div className={styles.columns}><TextField label="Pieza dental FDI" required inputMode="numeric" value={toothNumber} onChange={(event) => setToothNumber(event.target.value)} /><SelectField label="Superficie" value={surface} options={['GENERAL', 'OCCLUSAL', 'INCISAL', 'MESIAL', 'DISTAL', 'VESTIBULAR', 'BUCCAL', 'LINGUAL', 'PALATAL']} onChange={(event) => setSurface(event.target.value as ToothSurface)} /><TextField label="Código de condición" value={conditionCode} onChange={(event) => setConditionCode(event.target.value)} /><TextField label="Estado" value={status} onChange={(event) => setStatus(event.target.value)} /></div><TextArea label="Notas" rows={2} value={notes} onChange={(event) => setNotes(event.target.value)} /></InlineForm> }
