import { isApiError } from '../../../shared/api/problem'
export type ConsentStatus = 'PENDING' | 'SIGNED' | 'REVOKED' | 'VOIDED'
export interface ConsentTemplate { id: string; code: string; name: string; active: boolean; createdAt: string; updatedAt: string; version: number }
export interface ConsentTemplateVersion { id: string; templateId: string; versionNumber: number; contentMarkdown: string; contentHash: string; publishedAt: string; createdBy: string }
export interface PatientConsent { id: string; patientId: string; treatmentPlanId: string; templateVersionId: string; appointmentId: string; status: ConsentStatus; documentFileId: string; documentHash: string; signedAt: string; revokedAt: string; revocationReason: string; createdAt: string; version: number }
export interface ConsentSignature { id: string; consentId: string; signerName: string; signerRelationship: string; method: 'DRAWN' | 'DIGITAL_CONFIRMATION'; signedAt: string }
const text = (value: unknown) => typeof value === 'string' ? value : ''
export function fromTemplateDto(dto: any): ConsentTemplate { return { id: dto.id, code: dto.code, name: dto.name, active: dto.active, createdAt: dto.created_at, updatedAt: dto.updated_at, version: dto.version } }
export function fromTemplateVersionDto(dto: any): ConsentTemplateVersion { return { id: dto.id, templateId: dto.template_id, versionNumber: dto.version_number, contentMarkdown: dto.content_markdown, contentHash: dto.content_hash, publishedAt: dto.published_at, createdBy: dto.created_by } }
export function fromConsentDto(dto: any): PatientConsent { return { id: dto.id, patientId: dto.patient_id, treatmentPlanId: text(dto.treatment_plan_id), templateVersionId: dto.template_version_id, appointmentId: text(dto.appointment_id), status: dto.status, documentFileId: text(dto.document_file_id), documentHash: dto.document_hash, signedAt: text(dto.signed_at), revokedAt: text(dto.revoked_at), revocationReason: text(dto.revocation_reason), createdAt: dto.created_at, version: dto.version } }
export function fromSignatureDto(dto: any): ConsentSignature { return { id: dto.id, consentId: dto.consent_id, signerName: dto.signer_name, signerRelationship: text(dto.signer_relationship), method: dto.signature_method, signedAt: dto.signed_at } }
export const canSignConsent = (consent: PatientConsent) => consent.status === 'PENDING'
export const canRevokeConsent = (consent: PatientConsent, role: string) => consent.status === 'SIGNED' && role === 'OWNER_DENTIST'
export const canVoidConsent = (consent: PatientConsent, role: string) => consent.status === 'PENDING' && role === 'OWNER_DENTIST'
export const consentErrorMessage = (error: unknown) => { if (!isApiError(error)) return 'No pudimos completar el consentimiento. Intentá nuevamente.'; if (error.code === 'PRECONDITION_FAILED' || error.code === 'VERSION_CONFLICT' || error.status === 412) return 'El consentimiento cambió en otra sesión. Se conservaron tus datos y recargamos el estado actual.'; if (error.code === 'IMMUTABLE_CONSENT_EVIDENCE') return 'La evidencia del consentimiento es inmutable y esa acción ya no está permitida.'; if (error.code === 'CONSENT_EVIDENCE_MISMATCH') return 'El documento o la evidencia no corresponde a este consentimiento.'; if (error.code === 'FORBIDDEN') return 'Tu rol no tiene permiso para esta operación.'; return error.detail ?? 'Revisá los datos e intentá nuevamente.' }
export const isConsentConflict = (error: unknown) => isApiError(error) && (error.code === 'PRECONDITION_FAILED' || error.code === 'VERSION_CONFLICT' || error.status === 412)
